[package]
name = "pkgstrap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.23"
ron-reboot = "0.1.0-preview4"
serde = { version = "1", features = ["derive"] }
symlink = "0.1.0"
